x = linspace(-3,3);
y = linspace(-3,3);
[X, Y] = meshgrid(x, y);
f1 = exp(-x.^2);
f2 = exp(-(X.^2 + Y.^2));
subplot(2, 1, 1);
plot(x, f1);
title('Do thi y = e^{-x^2}');
xlabel('X');
ylabel('Y');
legend('y = e^{-x^2}');

subplot(2, 1, 2);
mesh(X, Y, f2);
title('Do thi z = e^{-(x^2 + y^2)}');
xlabel('X');
ylabel('Y');
zlabel('Z');
legend('z = e^{-(x^2 + y^2)}');
view(45, 45);